[ga]
num_generations = 1000
population_size = 130
mutation_rate = 0.05
crossover_rate = 0.9
num_trials = 80
n_elites_min = 15
n_elites_mean = 5
n_selected = 50
n_children = 80
n_elite_offspring = 10

[solver]
dt = 0.01
buffer_period = 2000
sampling_rate = 100




